### ISSUE TITLE
Can't get vision from clojars

### ISSUE THREAD

**Issue by ghost** [nakkaya/vision#2]
I've added `[org.clojars.nakkaya/vision "1.0.0"]` to my :dependencies, then run `lein deps` and got

```
[WARNING] POM for 'org.clojars.nakkaya:vision:pom:1.0.0:compile' is invalid. It will be ignored for artifact resolution. Reason: Not a v4.0.0 POM.
```

But if to clone repo manually and run `lein install` all works good. Maybe try to re-push it to clojars?

**Comment by nakkaya** [comment]
I pushed it again, should be fixed.
